//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.01 at 12:23:49 PM EEST
//


package models;


import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

@XmlType(name = "woodType")
@XmlEnum
public enum WoodType {

    @XmlEnumValue("oak")
    OAK("oak"),
    @XmlEnumValue("acacia")
    ACACIA("acacia"),
    @XmlEnumValue("walnut")
    WALNUT("walnut");
    private final String value;

    WoodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WoodType fromValue(String v) {
        for (WoodType c : WoodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}